namespace Fxcel.Core.Interop
{
    public enum XlApplicationInternational
    {
        xl24HourClock = 33,
        xl4DigitYears = 43,
        AlternateArraySeparator = 0x10,
        ColumnSeparator = 14,
        CountryCode = 1,
        CountrySetting = 2,
        CurrencyBefore = 37,
        CurrencyCode = 25,
        CurrencyDigits = 27,
        CurrencyLeadingZeros = 40,
        CurrencyMinusSign = 38,
        CurrencyNegative = 28,
        CurrencySpaceBefore = 36,
        CurrencyTrailingZeros = 39,
        DateOrder = 0x20,
        DateSeparator = 17,
        DayCode = 21,
        DayLeadingZero = 42,
        DecimalSeparator = 3,
        GeneralFormatName = 26,
        HourCode = 22,
        LeftBrace = 12,
        LeftBracket = 10,
        ListSeparator = 5,
        LowerCaseColumnLetter = 9,
        LowerCaseRowLetter = 8,
        MDY = 44,
        Metric = 35,
        MinuteCode = 23,
        MonthCode = 20,
        MonthLeadingZero = 41,
        MonthNameChars = 30,
        NoncurrencyDigits = 29,
        NonEnglishFunctions = 34,
        RightBrace = 13,
        RightBracket = 11,
        RowSeparator = 0xF,
        SecondCode = 24,
        ThousandsSeparator = 4,
        TimeLeadingZero = 45,
        TimeSeparator = 18,
        UpperCaseColumnLetter = 7,
        UpperCaseRowLetter = 6,
        WeekdayNameChars = 0x1F,
        YearCode = 19,
        UICultureTag = 46
    }
}
